name: scipp-tutorial
channels:
  - conda-forge
  - scipp
dependencies:
  - python=3.12
  - scipp >=24.8.0
  - jupyterlab >=4.2.4
  - h5py >=3.11.0
  - ipywidgets >=8.1.3
  - scipy >=1.14.0
  - matplotlib >=3.9.2
  - plopp >=24.6.0
  - pythreejs >=2.4.2
  - ipympl >=0.9.4
  - jupyterlab-myst >=2.4.2
  - graphviz >=12.0.0
  - python-graphviz >=0.20.3
  - curl >=8.9.1
