name: scipp-tutorial
channels:
  - conda-forge
  - scipp
dependencies:
  - python=3.11 
  - scipp >=24.6.0,<24.7
  - jupyterlab>=4.2.4,<4.3
  - h5py>=3.11.0,<3.12
  - ipywidgets>=8.1.3,<8.2
  - scipy>=1.14.0,<1.15
  - matplotlib>=3.9.1,<3.10
  - plopp>=24.6.0,<24.7
  - pythreejs>=2.4.2,<2.5
  - ipympl>=0.9.4,<0.10
  - python-graphviz>=0.20.3,<0.21
  - jupyterlab-myst>=2.4.2,<2.5
  - graphviz>=12.0.0,<12.1
