[project]
name = "scipp-tutorial-euroscipy24"
version = "0.1.0"
description = "Multi-dimensional arrays with Scipp"
authors = ["Mridul Seth <git@mriduls.com>"]
channels = ["conda-forge", "scipp"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tasks]

[dependencies]
scipp = ">=24.6.0,<24.7"
jupyterlab = ">=4.2.4,<4.3"
h5py = ">=3.11.0,<3.12"
ipywidgets = ">=8.1.3,<8.2"
scipy = ">=1.14.0,<1.15"
matplotlib = ">=3.9.1,<3.10"
plopp = ">=24.6.0,<24.7"
pythreejs = ">=2.4.2,<2.5"
ipympl = ">=0.9.4,<0.10"
python-graphviz = ">=0.20.3,<0.21"
jupyterlab-myst = ">=2.4.2,<2.5"
graphviz = ">=12.0.0,<12.1"
