[project]
name = "scipp-tutorial-euroscipy24"
version = "0.1.0"
description = "Multi-dimensional arrays with Scipp"
authors = ["Mridul Seth <git@mriduls.com>"]
channels = ["conda-forge", "scipp"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tasks]
download_data = { cmd = [
	"curl",
	"https://public.esss.dk/groups/scipp/dmsc-summer-school/scipp/nyc_taxi_data_2015_small.tar.gz",
	"--output",
	"nyc_taxi_data_2015_small.tar.gz"
] }
setup_data = { cmd = "python untar.py", depends-on = ["download_data"] }

[dependencies]
scipp = ">=24.8.0"
jupyterlab = ">=4.2.4"
h5py = ">=3.11.0"
ipywidgets = ">=8.1.3"
scipy = ">=1.14.0"
matplotlib = ">=3.9.2"
plopp = ">=24.6.0"
pythreejs = ">=2.4.2"
ipympl = ">=0.9.4"
jupyterlab-myst = ">=2.4.2"
graphviz = ">=12.0.0"
python-graphviz = ">=0.20.3"
curl = ">=8.9.1"
